apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432