apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.postgres.storage.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/postgres